# Generated by Django 4.2.5 on 2023-12-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0002_meeting_created_at_meeting_status_meeting_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='type',
            field=models.CharField(choices=[('public', 'Public Meeting'), ('private', 'Private Meeting'), ('asktojoin', 'Ask To Join Meeting'), ('onetoone', 'One To One Meeting')], max_length=15),
        ),
    ]
