# Generated by Django 4.2.5 on 2023-12-16 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meetings', '0005_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='chats',
            field=models.ManyToManyField(blank=True, null=True, related_name='chats', to='Meetings.chat'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
