# Generated by Django 4.2.5 on 2023-12-16 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meetings', '0006_alter_meeting_chats_alter_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='allowed_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='blacklisted_participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='blacklisted_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
