# Generated by Django 4.2.5 on 2023-12-17 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meetings', '0007_alter_meeting_allowed_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='chats',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
