# Generated by Django 4.2.5 on 2023-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='sdp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
